= Name Resolution

> THIS DOCUMENT IS A DRAFT AND IS NOT READY FOR REVIEW

== Scope

This document follows along with the _PartiQL-system_ implementation; it will be upstreamed to the specification once the PR is completed.

== Definitions

. **Catalog**: A named collection of _objects_ at the root (top-level) of a _PartiQL-system_.
. **Object**: A named item of a catalog; e.g. namespace, table, view, or routine.
. **Namespace**: A named collection of _objects_; namespaces can contain other namespaces.
. **Table**: A named value which is typically (but not necessarily) a collection of structs.
. **View**: A named query statement.
. **Routine**: A named function or procedure which is usable in a _statement_.
.. **Function**: A routine invoked in the context of a value expression.
.. **Procedure**: A routine invoked as a CALL statement.
. **Name**: An identifier associated with a _catalog_ or _object_.

== Concepts

=== Names

The following section gives a high-level description of the name resolution rules for tables and routines. Names are resolved using the current namespace _S_ and the session path _PATH_.

Names are either absolute or relative. An absolute name is always resolved from the root, and a relative name is resolved by prepending the current namespace to the relative name to form an absolute name.

.Name Syntax
[source]
----
name
 :     id ('.' id)*  # relative name
 | '.' id ('.' id)*  # absolute name
 ;

id
 : '"' symbol '"' # quoted identifier
 |     symbol     # symbol identifier
 ;

symbol: ...;
----

[cols="1e,1,2"]
|===
| Type | Form | Example

| Relative Name | `n~1~.---.n~n~` | `hello.world`
| Absolute Name | `.n~1~.---.n~n~` | `.goodnight.moon`

|===

== Name Resolution

=== Table Resolution

Let _N_ be a name (relative or absolute) with symbols _n~1~ , ... , n~i~_ and _S_ be the session namespace with name _. s~1~_ . s~2~ ... _s~j~_

. Let _T_ be the absolute table name.
.. If _N_ is relative, then _T = S + N = . s~1~ . s~2~ ... s~j~ . n~1~ . n~2~ ... n~i~_
.. If _N_ is absolute, then _T = N = . n~1~ . n~2~ ... n~i~_
. Let _n_ be the number of symbols in _T = . t~1~ . t~2~ ... t~n~_
. Find the largest _m ≤ n_ such that _t~1~ . t~2~ ... t~m~_ is a database name.
. Any remaining _t~m+1~ ...t~n~_ are path navigations.

=== Routine Resolution

// SQL 10.4

Let _N_ be a routine name with symbols _n~1~ , ... , n~i~_ and _S_ be the session namespace with name _. s~1~_ . s~2~ ... _s~j~_

. If n = 1 then the session path _PATH_ is searched left-to-right.
. Else let _R_ be the absolute routine name.
.. If _N_ is relative, then _R = S + N = . s~1~ . s~2~ ... s~j~ . n~1~ . n~2~. ... n~i~_ .
.. If _N_ is absolute, then _R = N = . n~1~ . n~2~ ... n~i~_
. Return all routines matching absolute name _R_.
