= Name Resolution

== Scope

This document defines the name resolution rules for tables, views, routines, and variables in the context of a xref:partiql-system.adoc[_PartiQL-System_] and a xref:partiql-system.adoc[_PartiQL-Session_].

== Definitions

[loweralpha,title="Names",start=1]
. **Name**: A relative or absolute name is composed of one or more identifiers.
. **Identifier**: A quoted or unquoted symbol.
. **Lookup Strategy**: Local-first or global-first lookup.

[loweralpha,title="From PartiQL-System",start=4]
. **Catalog**: A named collection of _objects_ at the root (top-level) of a _PartiQL-system_.
. **Namespace**: A named collection of _objects_; namespaces can contain other namespaces.
. **Object**: A named item of a catalog; e.g. namespace, table, view, or routine.

== Concepts

=== Names

Names composed of one or more identifiers which reference either a database object or a local variable. Identifiers are joined by a _<period>_ and a leading _<period>_ denotes an absolute name.

[cols="1e,1,2"]
|===
| Type | Form | Example

| Relative Name | `n~1~.---.n~n~` | `hello.world`
| Absolute Name | `.n~1~.---.n~n~` | `.goodnight.moon`

|===

.Name Syntax
[source,ebnf]
----
<name> ::= <relative name> | <absolute name>

<relative name> ::= <identifier> [ <period> <identifier> ]... 

<absolute name> ::= <period> <identifier> [ <period> <identifier> ]... 

<identifier>
    ::= <double quote> <symbol> <double quote>
      | <symbol>
----
// <period> ::= '.'
// <at> ::= '@'
// <symbol> ::= # [A-Za-z_][A-Za-z_0-9]*

// <value expression>
//     ::= <variable expression>
//       | <table expression>
//       | ....

// <variable expression>
//     ::= [ <at> ] <relative name>
//       | <absolute name>

// <table expression>
//     ::= <table reference>
//       | <value expression>

// <table reference> ::= <name>

=== Lookup Strategies

> INCOMPLETE

== Rules

Generally and absolute name is always resolved from the root, and a relative name is resolved by prepending the current namespace to the relative name to form an absolute name.

=== Table Resolution

Let _N_ be a name (relative or absolute) with symbols _n~1~ , ... , n~i~_ and _S_ be the session namespace with name _. s~1~_ . s~2~ ... _s~j~_

. Let _T_ be the absolute table name.
.. If _N_ is relative, then _T = S + N = . s~1~ . s~2~ ... s~j~ . n~1~ . n~2~ ... n~i~_
.. If _N_ is absolute, then _T = N = . n~1~ . n~2~ ... n~i~_
. Let _n_ be the number of symbols in _T = . t~1~ . t~2~ ... t~n~_
. Find the largest _m ≤ n_ such that _t~1~ . t~2~ ... t~m~_ is a database name.
. Any remaining _t~m+1~ ...t~n~_ are path navigations.

=== Routine Resolution

// SQL 10.4

Let _N_ be a routine name with symbols _n~1~ , ... , n~i~_ and _S_ be the session namespace with name _. s~1~_ . s~2~ ... _s~j~_

. If n = 1 then the session path _PATH_ is searched left-to-right.
. Else let _R_ be the absolute routine name.
.. If _N_ is relative, then _R = S + N = . s~1~ . s~2~ ... s~j~ . n~1~ . n~2~. ... n~i~_ .
.. If _N_ is absolute, then _R = N = . n~1~ . n~2~ ... n~i~_
. Return all routines matching absolute name _R_.

== Guide

> PLACEHOLDER